**Welcome to Numpy Tutorial**

NumPy is a Python library used for working with arrays.In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is faster than Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

In [4]:
import numpy as np

In [3]:
myarr= np.array([3,6,10,12,12345],np.int64)

In [5]:
myarr

array([    3,     6,    10,    12, 12345], dtype=int64)

In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# Array indexing

In [8]:
myarr[0]

3

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [7]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


array shape

In [10]:
myarr.shape

(5,)

In [11]:
myarr.dtype

dtype('int64')

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


create numpy with tuple

In [3]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


2D array

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


# slicing

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

**negative slicing**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


# Iterating

In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


# Searching Arrays

You can search an array for a certain value, and return the indexes that get a match. To search an array, use the where() method.

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


# Sorting

In [10]:
import numpy as np

arr = np.array(['vibhuti', 'Manas', 'Shitanshu'])

print(np.sort(arr))

['Manas' 'Shitanshu' 'vibhuti']


# Array Creation: Conversion from other Python structures


In [5]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [13]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [14]:
listarray.dtype

dtype('int32')

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [17]:
np.array({34,23,23})

array({34, 23}, dtype=object)